version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo this is prebuild phase
  build:
    commands:
      - mvn clean package
  post_build:
    commands:
      - mv target/*.jar ./Project2.jar

artifacts:
  files:
    - Project2.jar