version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo this is prebuild phase
      - aws s3 cp s3://starsteamapi-filecontents/application.yml ./src/main/resources
  build:
    commands:
      - mvn clean package
  post_build:
    commands:
      - mv target/*.jar ./Project2-1.0-SNAPSHOT.jar

artifacts:
  files:
    - Project2-1.0-SNAPSHOT.jar