version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      
  build:
    commands:
      - mvn clean package
  post_build:
    commands:
      - mv target/*.jar ./Project2-1.0-SNAPSHOT.jar

artifacts:
  files:
    - Project2-1.0-SNAPSHOT.jar