server:
  port: 5000
  servlet:
    context-path: /MovieApp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database-1.csdkp74gxjhy.us-east-1.rds.amazonaws.com:5432/postgres?currentSchema=stars_team
    username: postgres
    password: !Lpizzaman11

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate